svaarala/duktape-wiki

Home.md, HowtoFinalization.md
=> Migrate website finalization examples

Home.md, HowtoModules.md
=> Migrate website module examples

Home.md, HowtoVirtualProperties.md
=> Migrate website virtual properties examples

Home.md, HowtoPerformance.md
=> Migrate website performance guidance

Home.md, Portability.md
=> Migrate website portability notes

HowtoPerformance.md
=> Performance note on "undefined"

DebugClients.md, Home.md
=> Add page on debug clients

.travis.yml, HowtoNativeConstructor.md, README.md
Add a minimal Travis run with a FIXME grep. This is useful to ensure pull requests can have unfinished stuff (marked with FIXME) which then gets cleaned up before merge.
=> Add a minimal Travis run

HowtoNativeConstructor.md
Write an initial native constructor how-to.  This is a very frequently asked question so the article should be quite thorough eventually. Initially just need the basic usage.
=> Add an initial native constructor howto

ProjectsUsingDuktape.md
=> Migrate project list from duktape.org to wiki

ProjectsUsingDuktape.md
See https://github.com/svaarala/duktape/issues/385.
=> Add DuktapeJava project link

Home.md, HowtoAugmentErrorObjects.md
=> How to for augmenting error objects

HowtoModules.md
Also reword the howto a bit, the "Module search function" section is difficult to follow.
Fixes #94.
=> How to return a native function from modSearch

Home.md, InternalExternalPrototype.md
=> Add a page on internal/external prototype

DevelopmentSetup.md, Home.md
=> Add development setup page

Home.md, HowtoNativePersistentReferences.md
=> Add how-to on persistent native references

ProjectsUsingDuktape.md
=> Add JavaScript::Duktape to project list

ProjectsUsingDuktape.md
See: https://github.com/svaarala/duktape/issues/728.
=> Add Skookum JS project link

ProjectsUsingDuktape.md
See: https://github.com/kovidgoyal/dukpy
=> Add dukpy as python binding

ProjectsUsingDuktape.md
See https://github.com/svaarala/duktape/issues/880.
=> Add android-duktape project

Home.md, HowtoBareMetal.md
=> Add a very basic bare metal howto

ProjectsUsingDuktape.md
Add Swift bindings for Duktape
=> Add swift-duktape

ApiCTypes.md, Configuring2x.md, DevelopmentSetup.md, GettingStartedLineProcessing.md, GettingStartedPrimalityTesting.md, HowtoBareMetal.md, HowtoBuffers1x.md, HowtoBuffers2x.md, HowtoEditorConfiguration.md, HowtoFatalErrors.md, HowtoFunctionCalls.md, HowtoGlobalObjectReference.md, HowtoIterateArray.md, HowtoLightfuncs.md, HowtoModules.md, HowtoNativeConstructor.md, HowtoNativePersistentReferences.md, HowtoNonBmpCharacters.md, HowtoVirtualProperties.md, InternalExternalPrototype.md, Performance.md, Portability.md, PostEs5Features.md
See https://github.com/svaarala/duktape/issues/1892.
=> Use 'ECMAScript' spelling in Wiki

ProjectsUsingDuktape.md
See https://github.com/svaarala/duktape/issues/2068.
=> Add zabbix to projects page

ProjectsUsingDuktape.md
=> Add low.js to ProjectsUsingDuktape.md

ProjectsUsingDuktape.md
https://github.com/svaarala/duktape/issues/2079
=> Add slivar project link
